# ── Profil : Grossiste PharmRestock (port 8083) ────────────────────────────────
server.port=8083
app.default-grossiste=PharmRestock

spring.datasource.url=jdbc:mysql://localhost:3306/grossiste_db_3?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=dsi23admin
spring.datasource.password=dsi23admin
