# ── Profil : Grossiste MedicaLab (port 8081) ──────────────────────────────────
server.port=8081
app.default-grossiste=MedicaLab

spring.datasource.url=jdbc:mysql://localhost:3306/grossiste_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=dsi23admin
spring.datasource.password=dsi23admin
